#!/bin/bash
DOTFILES_BASE="$(cd "$(dirname "$0")/../" && pwd)"
rm -f ~/.bash_profile
ln -sf "$DOTFILES_BASE"/.bash_profile ~/.bash_profile
ln -sf "$DOTFILES_BASE"/.gitignore_global ~/.gitignore_global
source ~/.bash_profile
git config --global core.excludesfile ~/.gitignore_global
