#!/bin/bash
set -e

if [ "$1" == "--debug" ]; then
  set -x
fi

DIR="$(cd "$(dirname "$0")/../" && pwd)"

# Use .bash_profile from dotfiles
install_bash_profile() {
  BASH_PROFILE="$HOME/.bash_profile"
  echo "👨🏻‍💻 Installing .bash_profile..."
  ln -sf "$DIR"/.bash_profile "$BASH_PROFILE"
}

# Use .gitignore_global from dotfiles
install_gitignore() {
  echo "🙈 Installing .gitignore_global..."
  ln -sf "$DIR"/.gitignore_global ~/.gitignore_global
  git config --global core.excludesfile ~/.gitignore_global
}

# Use .gitignore_global from dotfiles
install_bash_it() {
  echo "🐚 Installing bash-it"
  BASH_IT="$HOME/.bash-it"
  if [ ! -d "$BASH_IT" ] ; then
    git clone --quiet --depth=1 https://github.com/Bash-it/bash-it.git "$BASH_IT"
  fi
}

install_powerline_fonts() {
  echo "🔠 Installing powerline-fonts..."
  POWERLINE_FONTS="$HOME/.powerline-fonts"
  if [ ! -d "$POWERLINE_FONTS" ] ; then
    git clone https://github.com/powerline/fonts.git --quiet --depth=1 "$POWERLINE_FONTS"
  fi
  bash "$POWERLINE_FONTS/install.sh" >> /dev/null
}

configure_iterm2() {
  if [ "$(uname)" == "Darwin" ] ; then
    echo "👾 Configuring iTerm2..."
    defaults import com.googlecode.iTerm2 "$DIR"/config/iterm2/com.googlecode.iterm2.plist
  fi
}

partytime() {
  echo -e "\n🤙 Looks like we're good to go! Open a new shell!"
}

# Do the things...
install_bash_profile
install_gitignore
install_bash_it
install_powerline_fonts
configure_iterm2

partytime
