#!/bin/bash
set -e

if [ "$1" == "--debug" ]; then
  set -x
fi

DIR="$(cd "$(dirname "$0")/../" && pwd)"
BREWFILE="/Users/rypit/projects/homebrew-brewfile/Brewfile"

# Install Homebrew if missing
install_homebrew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "🍺 Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
}

# Run brew bundle
run_brew_bundle() {
  echo "📦 Running brew bundle..."
  brew bundle --file="$BREWFILE"
}

# Install .zshrc and .zsh_plugins.txt
install_zsh_config() {
  echo "👨🏻‍💻 Installing Zsh configuration..."
  ln -sf "$DIR"/.zshrc "$HOME/.zshrc"
  ln -sf "$DIR"/.zsh_plugins.txt "$HOME/.zsh_plugins.txt"
  if [ -f "$DIR/p10k.zsh" ]; then
    ln -sf "$DIR/p10k.zsh" "$HOME/.p10k.zsh"
  fi
}

# Configure shell to zsh
configure_shell() {
  echo "🐚 Configuring shell to zsh..."
  ZSH_PATH="$(which zsh)"
  if [ "$SHELL" != "$ZSH_PATH" ]; then
    chsh -s "$ZSH_PATH"
  fi
}

# Use .gitignore_global from dotfiles
install_gitignore() {
  echo "⚙️  Configuring git..."
  ln -sf "$DIR/.gitignore_global" "$HOME/.gitignore_global"
  git config --global core.excludesfile "$HOME/.gitignore_global"
  git config --global push.default current
}

configure_iterm2() {
  if [ "$(uname)" == "Darwin" ]; then
    echo "👾 Configuring iTerm2..."
    defaults import com.googlecode.iTerm2 "$DIR"/config/iterm2/com.googlecode.iterm2.plist
  fi
}

configure_macOS() {
  if [ "$(uname)" == "Darwin" ]; then
    echo "🍏 Configuring macOS..."
    bash "$DIR/script/macos"
  fi
}

partytime() {
  echo -e "\n🤙 Modernization complete! Open a new Zsh shell and enjoy 'ghostly' theme!"
}

# Do the things...
install_homebrew
run_brew_bundle
configure_shell
install_zsh_config
install_gitignore
configure_iterm2
configure_macOS

partytime
