#!/bin/bash

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

###############################################################################
# General UI/UX                                                               #
###############################################################################

echo "🍎 Configuring General UI/UX..."

# Disable "Look up & data detectors" (the "stupid dictionary thing")
# Internal Trackpad
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerTapGesture -int 0
# Bluetooth Trackpad
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerTapGesture -int 0
# Global host setting
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerTapGesture -int 0

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                #
###############################################################################

echo "🖱️ Configuring Trackpad & Input..."

# Enable Right-Click (Secondary Click - Bottom Right Corner)
# Internal Trackpad
defaults write com.apple.AppleMultitouchTrackpad TrackpadRightClick -bool false
defaults write com.apple.AppleMultitouchTrackpad TrackpadCornerSecondaryClick -int 2
# Bluetooth Trackpad
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool false
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
# Global host setting
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 2

# Enable "natural" (Lion-style) scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true

###############################################################################
# Finder                                                                      #
###############################################################################

echo "📂 Configuring Finder..."

# Finder: set list view as default
# Use list view in all Finder windows by default
# Four-letter codes for the other views: `icnv`, `clmv`, `glyv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Remove items from the Trash after 30 days
defaults write com.apple.finder FXRemoveOldTrashItems -bool true

# New window target -> Home folder
defaults write com.apple.finder NewWindowTarget -string "PfHm"

###############################################################################
# Dock                                                                        #
###############################################################################

echo "📥 Configuring Dock..."

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Don’t show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

###############################################################################
# Finalize                                                                    #
###############################################################################

echo "♻️  Restarting affected apps..."

for app in "Dock" "Finder"; do
  killall "$app" > /dev/null 2>&1
done

echo "✅ macOS configuration applied surgically. Note that some changes may require a logout/restart to take effect."
