#!/bin/bash
# shellcheck disable=SC2046
RESULT=$(shellcheck -e SC1090,SC1091 script/* .zshrc)
if [ "$RESULT" == "" ] ; then
  echo "✅ Shellcheck passed"
else
  echo "❌ Shellcheck failed"
  echo "$RESULT"
  exit 1;
fi
