name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run bootstrap
        run: ./script/bootstrap --debug

      - name: Run tests
        run: ./script/test
